#!/bin/bash
echo;

# Check if bridge-utils package is installed
if ! dpkg -s bridge-utils &> /dev/null; then
  echo "The bridge-utils package is not installed."
  echo "Please install it by running the command: sudo apt install bridge-utils"
  echo "Type 'ok' to exit..."
  read resposta
  if [ "$resposta" = "ok" ]; then
    exit
  fi
else
  echo "The bridge-utils package is already installed."
fi

    # Default network settings
bridge_ip=192.168.0.178
broadcast=192.168.0.255
netmask=255.255.255.0
gateway=192.168.0.1


echo;
echo "Configuring /etc/network/interfaces to turn off bridge br0 and turn on Default Network Manager Connection";
echo "..."
echo "";
echo "sudo brctl show; #(show bridges and interfaces connected...";
sudo brctl show;
read -rp "Enter the network interface that bridge br0 is using: " interface
echo "The chosen network interface is: $interface"
echo "";
echo "";
echo "sudo brctl delif br0 $interface;";
sudo brctl delif br0 $interface;
echo "";
echo "sudo ip link set br0 down;";
sudo ip link set br0 down;
echo "";
echo "sudo brctl delif br0 $interface;";
sudo brctl delif br0 $interface;
echo "";
echo "sudo brctl delbr br0;";
sudo brctl delbr br0;
echo "";
echo "sudo ip link delete br0;";
sudo ip link delete br0;
echo "";
echo "sudo brctl delif br0 $interface;";
sudo brctl delif br0 $interface;

echo;
sudo cat > /etc/network/interfaces << EOF


# This file describes the network interfaces available on your system
# and how to activate them. For more information, see interfaces(5).

#Debian Default Configuration with no bridges...
source /etc/network/interfaces.d/*

# The loopback network interface
auto lo
iface lo inet loopback



#BRIDGE BR0 SETTING FOR STATIC IP $bridge_ip
#adicione
# The loopback network interface
#auto lo br0
#iface lo inet loopback

# Set up interfaces manually, avoiding conflicts with, e.g., network manager
#iface $interface inet manual

# Bridge setup
#auto br0
#iface br0 inet static
#bridge_ports $interface
#address $bridge_ip
#broadcast $broadcast
#netmask $netmask
#gateway $gateway



EOF
echo;

echo "Restarting Network Manager Harding (stop, disable, enable, start)";
sudo systemctl stop NetworkManager;
sudo systemctl disable NetworkManager;
sudo systemctl enable NetworkManager;
sudo systemctl start NetworkManager;

echo "Configured /etc/network/interfaces to Default Network Settings";
echo;
echo "cat /etc/network/interfaces";
cat /etc/network/interfaces;
echo;
echo "Reboot to Restart if is not working..."












